services:
  db:
    image: postgres:17.6
    container_name: tcc_financeiro_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${DB_EXTERNAL_PORT}:5432"

  app:
    build:
      context: ./docker/php
    container_name: tcc_financeiro_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html

  nginx:
    image: nginx:stable
    container_name: tcc_financeiro_nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8001}:80" 
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - node

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: tcc_financeiro_node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
    command: bash -c "npm install && npm run dev"
    ports:
      - "5173:5173"

volumes:
  db_data: